spring.application.name=ohmeomuk
spring.config.import=optional:file:../.env[.properties],optional:file:.env[.properties]
kakao.api-key=${KAKAO_REST_API_KEY:${kakao_map_api:}}
server.address=${SERVER_ADDRESS:127.0.0.1}
server.port=${PORT:8080}
server.error.include-message=never
server.error.include-stacktrace=never
spring.mvc.log-request-details=false
